<?php

/**
 * Security configuration
 */

return [
    'key' => 'your-secret-key',
    'cipher' => 'AES-256-CBC',
    'hash' => 'sha256',
    'hash_key' => 'your-hash-key',
    'hash_algo' => 'sha256',
    'hash_options' => [
        'cost' => 12,
    ],
    'csrf' => [
        'key' => 'csrf-token',
        'expires' => 3600,
    ],
    'cors' => [
        'enabled' => false,
        'origin' => '*',
        'methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        'headers' => ['Content-Type', 'Authorization'],
        'exposed' => [],
        'max_age' => 0,
    ],
    'jwt' => [
        'enabled' => false,
    ],
    'recaptcha' => [
        'enabled' => false,
        'site_key' => '',
    ],
    'encryption' => [
        'enabled' => false,
        'key' => 'your-encryption-key',
        'cipher' => 'AES-256-CBC',
    ],
    'hashids' => [
        'enabled' => false,
        'salt' => 'your-salt',
        'length' => 10,
    ],
    'password' => [
        'algorithm' => PASSWORD_DEFAULT,
        'options' => [
            'cost' => 12,
        ],
    ],
    'otp' => [
        'length' => 6,
        'ttl' => 300,
    ],
    'auth' => [
        'enabled' => false,
        'model' => 'App\Models\User',
        'field' => 'email',
        'password' => 'password',
        'remember' => 'remember_token',
        'otp' => 'otp',
        'jwt' => 'jwt',
        'hash' => 'hash',
        'hash_algo' => 'sha256',
        'hash_options' => [
            'cost' => 12,
        ],
    ],
    'session' => [],
    'cookies' => [],
    'headers' => [
        'x-frame-options' => 'DENY',
        'x-xss-protection' => '1; mode=block',
        'x-content-type-options' => 'nosniff',
        'referrer-policy' => 'no-referrer',
        'feature-policy' => '',
    ],
    'content_security_policy' => [
        'enabled' => false,
        'directives' => [
            'default-src' => "'self'",
            'script-src' => "'self'",
            'style-src' => "'self'",
            'img-src' => "'self'",
            'connect-src' => "'self'",
            'font-src' => "'self'",
            'object-src' => "'none'",
            'media-src' => "'none'",
            'frame-src' => "'none'",
            'sandbox' => '',
            'base-uri' => "'self'",
            'form-action' => "'self'",
            'frame-ancestors' => "'none'",
            'manifest-src' => "'self'",
            'prefetch-src' => "'self'",
            'worker-src' => "'self'",
            'child-src' => "'self'",
            'navigate-to' => "'self'",
            'report-uri' => '',
            'block-all-mixed-content' => false,
            'upgrade-insecure-requests' => false,
            'plugin-types' => '',
            'require-sri-for' => '',
            'report-to' => '',
        ],
    ],
    'hsts' => [
        'enabled' => false,
        'max_age' => 31536000,
        'include_subdomains' => false,
        'preload' => false,
    ],
    'referrer_policy' => [
        'enabled' => false,
        'policy' => 'no-referrer',
    ],
    'feature_policy' => [
        'enabled' => false,
        'directives' => [
            'accelerometer' => "'none'",
            'ambient-light-sensor' => "'none'",
            'autoplay' => "'none'",
            'camera' => "'none'",
            'document-domain' => "'none'",
            'encrypted-media' => "'none'",
            'fullscreen' => "'none'",
            'geolocation' => "'none'",
            'gyroscope' => "'none'",
            'magnetometer' => "'none'",
            'microphone' => "'none'",
            'midi' => "'none'",
            'payment' => "'none'",
            'picture-in-picture' => "'none'",
            'publickey-credentials-get' => "'none'",
            'sync-xhr' => "'none'",
            'usb' => "'none'",
            'wake-lock' => "'none'",
            'xr-spatial-tracking' => "'none'",
        ],
    ],
    'csp' => [
        'enabled' => false,
        'directives' => [
            'default-src' => "'self'",
            'script-src' => "'self'",
            'style-src' => "'self'",
            'img-src' => "'self'",
            'connect-src' => "'self'",
            'font-src' => "'self'",
            'object-src' => "'none'",
            'media-src' => "'none'",
            'frame-src' => "'none'",
            'sandbox' => '',
            'base-uri' => "'self'",
            'form-action' => "'self'",
            'frame-ancestors' => "'none'",
            'manifest-src' => "'self'",
            'prefetch-src' => "'self'",
            'worker-src' => "'self'",
            'child-src' => "'self'",
            'navigate-to' => "'self'",
            'report-uri' => '',
            'block-all-mixed-content' => false,
            'upgrade-insecure-requests' => false,
            'plugin-types' => '',
            'require-sri-for' => '',
            'report-to' => '',
        ],
    ],
    'csp_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'csp_report_only' => [
        'enabled' => false,
        'directives' => [
            'default-src' => "'self'",
            'script-src' => "'self'",
            'style-src' => "'self'",
            'img-src' => "'self'",
            'connect-src' => "'self'",
            'font-src' => "'self'",
            'object-src' => "'none'",
            'media-src' => "'none'",
            'frame-src' => "'none'",
            'sandbox' => '',
            'base-uri' => "'self'",
            'form-action' => "'self'",
            'frame-ancestors' => "'none'",
            'manifest-src' => "'self'",
            'prefetch-src' => "'self'",
            'worker-src' => "'self'",
            'child-src' => "'self'",
            'navigate-to' => "'self'",
            'report-uri' => '',
            'block-all-mixed-content' => false,
            'upgrade-insecure-requests' => false,
            'plugin-types' => '',
            'require-sri-for' => '',
            'report-to' => '',
        ],
    ],
    'csp_report_only_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'referrer_policy_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'feature_policy_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'hsts_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'security_policy' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'security_policy_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'xss_protection_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'content_type_options_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'frame_options_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'expect_ct_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'x_content_type_options_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'x_frame_options_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
    'x_xss_protection_report' => [
        'enabled' => false,
        'report_uri' => '',
    ],
];
